### ISSUE TITLE
gen proto issue

### ISSUE THREAD

**Issue by tocomp** [bufbuild/protovalidate-go#104]
Which protoc extension is used for protovalidate-go generation? The github.com/envoyproxy/protoc-gen-validate/validate tool no longer exists

**Comment by nicksnyder** [comment]
The `protovalidate` project does not have a code-generation component, the validation rules are determined at runtime via proto reflection by the libraries.

The README documentation on [protovalidate](https://github.com/bufbuild/protovalidate#usage) and [protovalidate-go](https://github.com/bufbuild/protovalidate-go#usage) walks through the process of using this project.
