### ISSUE TITLE
[BUG] Some red wavy line about importing  when VSCode/Goland displaying generated code

### ISSUE THREAD

**Issue by TremblingV5** [bufbuild/protovalidate-go#112]
Hi everyone!

I'm new to this repo, so it's maybe a foolish question. In fact, this issue may not a bug. Because my app work good with generated code.

## Description

In generated code, there're some lines of importing:

```golang
import(
    _ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
)
```

VSCode marked it with red wavy line, and tell me there's an error here

> could not import buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate (no required module provides package "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate") compiler [BrokenImport](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport)

But my app work good when I using `go build`.

I'm using `.proto` files like following:

```proto
syntax = "proto3";

package xxx;

import "api/grpc/entities/error.proto";
import "xxxxxx"; // some other proto files defined by me
import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "openapiv3/annotations.proto";

option go_package = "xxx";

service XXX{
    ......
}

......
```

I hope VSCode does not display red wavy lines

## Steps to Reproduce

1. Write proto files
2. Use protoc to generate some pb code

## Expected Behavior

No red wavy lines.

## Environment

- **Operating System**: 
- **Version**: 
- **Compiler/Toolchain**: 
- **Protobuf Compiler & Version**: 
- **Protoc-gen-validate Version**: 
- **Protovalidate Version**:

**Comment by rodaine** [comment]
Hi @TremblingV5! Moved to `protovalidate-go` since it's specific to the Go implementation.

That error indicates the imported package does not have a corresponding required module in your `go.mod` file. A `go mod tidy` or even `go build ./...` would update the your dependencies to include that requirement. The error should go away after that, though it is at the whim of VSCode and the Go LSP.

**Comment by TremblingV5** [comment]
> Hi @TremblingV5! Moved to `protovalidate-go` since it's specific to the Go implementation.
> 
> That error indicates the imported package does not have a corresponding required module in your `go.mod` file. A `go mod tidy` or even `go build ./...` would update the your dependencies to include that requirement. The error should go away after that, though it is at the whim of VSCode and the Go LSP.

Hi @rodaine ， thanks for your advices !

I know that it's a wavy line about dependencies, so I tried `go mod tidy` earlier. But the red wavy line still here. I will try it again, I will comment this issue again laterly.

**Comment by TremblingV5** [comment]
Hi @rodaine , thanks for your advices again!

I tried `go mod tidy` again. But the red wavy line still here, and I reopen project in IDE the red wavy lines has gone away. Maybe this question caused by cache of IDE.

Totally, the red wavy lines has gone away.
