### ISSUE TITLE
[BUG] resolveDeprecatedIndex() isn't functioning.

### ISSUE THREAD

**Issue by ogoshikazuki** [bufbuild/protovalidate-go#116]
## Description

[resolveDeprecatedIndex()](https://github.com/bufbuild/protovalidate-go/blob/8f25afb647e12157cfc666d49dafe57904355c68/resolver/resolver.go#L95-L108) isn't functioning.
In my project, the version of the buf module in protovalidate was fixed to [commit 998a6885b3f74d08847b9c24571fdf08](https://legalon-technologies.buf.dev/bufbuild/protovalidate/docs/998a6885b3f74d08847b9c24571fdf08) in buf.lock.
[Commit 998a6885b3f74d08847b9c24571fdf08 has an old extension field number of 51071.](https://legalon-technologies.buf.dev/bufbuild/protovalidate/docs/998a6885b3f74d08847b9c24571fdf08:buf.validate#extensions)
Even so, protovalidate-go was functioning up to [v0.3.2](https://github.com/bufbuild/protovalidate-go/releases/tag/v0.3.2), but stopped working from [v0.3.3](https://github.com/bufbuild/protovalidate-go/releases/tag/v0.3.3).
I suspect the cause is in https://github.com/bufbuild/protovalidate-go/pull/57.

## Steps to Reproduce

1. In buf.yaml, you would include the following:
```yaml
deps:
  - buf.build/bufbuild/protovalidate:998a6885b3f74d08847b9c24571fdf08
```
2. `buf mod update`
3. `buf generate`
4. protovalidate-go functions with v0.3.2 but does not function with v0.3.3.

## Expected Behavior

Even if the buf module version of protovalidate is old, protovalidate-go@v0.3.3 and later will function.

## Actual Behavior

When the version of the buf module in protovalidate is commit 998a6885b3f74d08847b9c24571fdf08 and protovalidate-go is at v0.3.3, protovalidate-go does not function.

## Screenshots/Logs

Nothing.

## Environment

- **Operating System**: macOS
- **Version**: macOS 14.3.1
- **Compiler/Toolchain**: Go1.22.2
- **Protobuf Compiler & Version**: buf v1.28.1
- **Protoc-gen-validate Version**: v0.3.3 and later
- **Protovalidate Version**: [commit 998a6885b3f74d08847b9c24571fdf08](https://legalon-technologies.buf.dev/bufbuild/protovalidate/docs/998a6885b3f74d08847b9c24571fdf08)

## Possible Solution

I suspect the cause is in https://github.com/bufbuild/protovalidate-go/pull/57.

## Additional Context

Nothing.

**Comment by rodaine** [comment]
Hey, @ogoshikazuki! Thanks for the great bug report. Wrote up a quick patch that should fix the issue!

**Comment by ogoshikazuki** [comment]
@rodaine 
When do you plan to release this?

**Comment by rodaine** [comment]
Released! https://github.com/bufbuild/protovalidate-go/releases/tag/v0.6.2
