### ISSUE TITLE
[BUG] string min_len and ignore_empty

### ISSUE THREAD

**Issue by jbaldwinroberts** [bufbuild/protovalidate-go#137]
## Description
This works as expected in `V0.3.1` but it does not work in `V0.6.x`

```
  optional string description = 2 [
    (buf.validate.field).string = {
      min_len: 5,
      max_len: 100
    },
    (buf.validate.field).ignore_empty = true,
  ];
  ```

## Steps to Reproduce
Use the above config with `V0.3.1` and `V0.6.x`, the behaviour will be different.

## Expected Behavior
Using `V0.6.x` with the above validation config.
When description is not empty it should validate the length is between 5 and 100.
When the description is empty it should not validate the length.

## Actual Behavior
Using `V0.6.x` with the above validation config.
When description is not empty it should validate the length is between 5 and 100.
When the description is empty it returns `validation error:\n - description: value length must be at least 5 characters [string.min_len]`

**Comment by rodaine** [comment]
Hi @jbaldwinroberts! There were changes in the semantics of `ignore_empty` introduced in 0.4.1 to clarify what is meant by "empty." For an `optional` field, "empty" means unset or nil. If you set it to the empty string (`""`), that is an actual value (and it's encoded in the wire format), so validation applies. 

`ignore_empty` is now also deprecated in favor of the more flexible `ignore` option. What you'll want is `ignore = IGNORE_IF_DEFAULT_VALUE`, which will skip validation if the field is unpopulated OR the default value.
