### ISSUE TITLE
[BUG] priv error

### ISSUE THREAD

**Issue by vet1ments** [bufbuild/protovalidate-go#145]
buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go v1.34.2-20240717164558-a6c49f84cc0f.2 is ok
but
buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go v1.34.2-20240920164238-5a7b106cbb87.2 
in this version raise not found "priv.."  (i dont know the detail) error

buf.yaml
```buf.yaml
version: v2
modules:
  - path: proto
lint:
  use:
    - STANDARD
breaking:
  use:
    - FILE
deps:
  - buf.build/bufbuild/protovalidate
```
buf,gen.yaml
```buf.gen.yaml
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: github.com/vet1ments/grpcoauth/go
  disable:
    - file_option: go_package_prefix
      module: buf.build/bufbuild/protovalidate
plugins:
  - local: protoc-gen-grpclib_python # async stub
    out: python
  - remote: buf.build/protocolbuffers/python:v28.2
    out: python
  - remote: buf.build/protocolbuffers/pyi:v28.2
    out: python
  - remote: buf.build/grpc/python
    out: python
  - remote: buf.build/protocolbuffers/go:v1.34.2
    out: go
    opt: paths=source_relative
  - remote: buf.build/connectrpc/go:latest
    out: go
    opt: paths=source_relative
  - remote: buf.build/grpc/go
    out: go
    opt: paths=source_relative
inputs:
  - directory: proto
```

**Comment by jchadwick-buf** [comment]
Sorry about this: it is an unintended consequence of a breaking change that occurred in `protovalidate`. It's my own oversight, I didn't realize Go would start pulling the latest `protovalidate` changes before we updated the module in `protovalidate-go`.

Please stick to using version `v1.34.2-20240717164558-a6c49f84cc0f.2` of the gencode for now. We will work on shipping the changes that fix this in https://github.com/bufbuild/protovalidate-go/pull/144 ASAP.

**Comment by vet1ments** [comment]
thank you so much for comfirming
