### ISSUE TITLE
[QUESTION] validate.proto file not found after running "go get -u github.com/bufbuild/protovalidate-go"

### ISSUE THREAD

**Issue by toma3233** [bufbuild/protovalidate-go#43]
## Description
I am trying to use protovalidate-go in my go project in an effort to add input validation to a variable in my "api.proto" file. I am also using protovalidate interceptor from go-grpc-middleware to intercept any cases where there is invalid input. 

## Steps to Reproduce

1. Run go get -u github.com/bufbuild/protovalidate-go
2. Run protoc --proto_path=. --proto_path=../../../../go/pkg/mod/github.com/bufbuild/protovali
date-go@v0.3.1 --go_out=. --go_opt=paths=source_relative --protovalidate_go_out=. api.proto  [[go directory in my root folder]]
3. Get the following errors:
 buf/validate/validate.proto: File not found.
api.proto:6:1: Import "buf/validate/validate.proto" was not found or had errors.

## Expected Behavior

Expected for it to find the validate.proto file but it doesn't. Please let me know if I am doing something wrong

## Screenshots/Logs
![image](https://github.com/bufbuild/protovalidate-go/assets/38714456/02f44585-a975-49a3-a692-c69aca407937)

## Environment

- **Operating System**: WSL 2
- **Version**: Ubuntu 22.04.3 LTS

**Comment by timostamm** [comment]
Hey Tom, since the project has been split into separate repositories - one per language implementation - validate.proto is no longer part of the go module. 

You can vendor the [relevant proto files](https://github.com/bufbuild/protovalidate/tree/main/proto/protovalidate) in your repository, and add an `--proto_path` flag to to the directory in your command.

**Comment by technodrome** [comment]
> Hey Tom, since the project has been split into separate repositories - one per language implementation - validate.proto is no longer part of the go module.
> 
> You can vendor the [relevant proto files](https://github.com/bufbuild/protovalidate/tree/main/proto/protovalidate) in your repository, and add an `--proto_path` flag to to the directory in your command.

Hi @timostamm . Where exactly is this in the documentation? Is the user of the module expected to manually sync changes in the validate.proto? Hope not, this is far from elegant. What's your envisioned workflow exactly?

**Comment by rodaine** [comment]
Hi @technodrome and @toma3233! This repo's [README](https://github.com/bufbuild/protovalidate-go#implementing-validation-constraints) links to instructions on the core protovalidate project's [usage instructions](https://github.com/bufbuild/protovalidate#import-protovalidate), which includes details on how to include the necessary protos into your project. This library depends on the code generation directly and therefore does not include the proto files in its module (either directly or transitively).

That said, we're always open to improving our documentation to make the workflow clearer. We're happy to field any suggestions.
