### ISSUE TITLE
[BUG]  undefined: atomic.Pointer v0.3.3

### ISSUE THREAD

**Issue by kailashyogeshwar85** [bufbuild/protovalidate-go#61]
## Steps to Reproduce

1. go get github.com/bufbuild/protovalidate-go@v0.3.3
2. kratos run

GO_PATH/pkg/mod/github.com/bufbuild/protovalidate-go@v0.3.3/internal/evaluator/builder.go:34:21: undefined: atomic.Pointer 

## Actual Behavior
Program terminates

## Environment

  - **Operating System**: linux>
- **Version**: Ubuntu 20.04
- **Compiler/Toolchain**: GCC 9.4.0
- **Protobuf Compiler & Version**: protoc 24.x
- **Protoc-gen-validate Version**: NA
- **Protovalidate Version**: v1.31.0

## Additional Context

Works when download protovalidate-go to v0.2.0

**Comment by nicksnyder** [comment]
Thanks for the bug report. It looks like in https://github.com/bufbuild/protovalidate-go/pull/31 we introduced a dependency on [atomic.Pointer](https://pkg.go.dev/sync/atomic#Pointer), which requires Go 1.19, but we forgot to update the minimum required version in go.mod and we can get this fixed.

I assume that you are using Go 1.18 or earlier? If so, the solution is to either upgrade Go to 1.19 or later or downgrade protovalidate to v0.3.1 or earlier.
