### ISSUE TITLE
[Feature Request] Allow extending default cel.Env created by protovalidate.New

### ISSUE THREAD

**Issue by kralicky** [bufbuild/protovalidate-go#73]
**Feature description:** 

It would be great if we could extend the default env with custom options, while using the builtin Validator.

**Problem it solves or use case:** 

I'd like to add my own cel functions and/or modify existing ones, and have them be available when validating using a validator created by protovalidate.New(...).

**Proposed implementation or solution:** 

One way could be to add a ValidatorOption like `WithEnvOptions(...cel.EnvOption)`, which would do the following:

 ```diff
 func New(options ...ValidatorOption) (*Validator, error) {
 	cfg := config{resolver: resolver.DefaultResolver{}}
 	for _, opt := range options {
 		opt(&cfg)
 	}
 
 	env, err := celext.DefaultEnv(cfg.useUTC)
 	if err != nil {
 		return nil, fmt.Errorf(
 			"failed to construct CEL environment: %w", err)
 	}
 
+	if len(cfg.envOpts) > 0 {
+		env, err = env.Extend(cfg.envOpts...)
+		if err != nil {
+			return nil, fmt.Errorf(
+				"failed to extend CEL environment: %w", err)
+		}
+	}
 
 	bldr := evaluator.NewBuilder(
 		env,
 		cfg.disableLazy,
 		cfg.resolver,
 		cfg.desc...,
 	)
 
 	return &Validator{
 		failFast: cfg.failFast,
 		builder:  bldr,
 	}, nil
 }
 ```

Then, 
```go
v, err := protovalidate.New(protovalidate.WithEnvOptions(...))
...
```

**Contribution:**

I would be willing to contribute this.

**Examples or references:** 

**Additional context:** 

Thanks! :smiley:

**Comment by bhollis** [comment]
Amazing, I just came here to file the exact same request :-)

**Comment by kralicky** [comment]
That design ended up having some limitations, notably I needed to be able to access the Env's `CELTypeProvider()` and `CELTypeAdapter()` to use custom protobuf message types as function inputs/outputs. The updated implementation is here: https://github.com/kralicky/protovalidate-go/commit/da6dae88b56f67cde598fea5b8a9ffdadb4181cd

Here's an example of how I used it:
```proto
message X509Certificate {
  bytes                     raw       = 1;
  bool                      isCA      = 2;
  string                    issuer    = 3;
  string                    subject   = 4;
  google.protobuf.Timestamp notBefore = 5;
  google.protobuf.Timestamp notAfter  = 6;
  string                    alg       = 7;
}
```
```go
protovalidate.New(
  protovalidate.WithExtendFunc(func(e *cel.Env) []cel.EnvOption {
    tr := env.CELTypeProvider().(*types.Registry)
    tr.RegisterMessage(&X509Certificate{})

    return []cel.EnvOption {
      cel.Function("x509Parse",
        cel.Overload("str_parse_x509",
          []*cel.Type{cel.StringType},
          cel.ObjectType(string(proto.MessageName(&X509Certificate{}))),
          cel.UnaryBinding(func(value ref.Val) ref.Val {
            str, ok := value.Value().(string)
            if !ok {
              return types.UnsupportedRefValConversionErr(value)
            }
            block, _ := pem.Decode([]byte(str))
            if block == nil {
              return types.NewErr("malformed PEM block")
            }

            cert, err := x509.ParseCertificate(block.Bytes)
            if err != nil {
              return types.WrapErr(err)
            }
            return env.CELTypeAdapter().NativeToValue(&X509Certificate{
              Raw:       cert.Raw,
              IsCA:      cert.IsCA,
              Issuer:    cert.Issuer.String(),
              Subject:   cert.Subject.String(),
              NotBefore: timestamppb.New(cert.NotBefore),
              NotAfter:  timestamppb.New(cert.NotAfter),
              Alg:       cert.PublicKeyAlgorithm.String(),
            })
          }),
        ),
      ),
    }
  }),
)
```

Then I can write, for example:

```
expression: "x509Parse(this.certData).issuer == 'foo'"
``` 
or pass it to some other methods:
```
expression: "x509Parse(this.certData).checkSignatureFrom(x509Parse(this.caCertData))"
```

**Comment by rodaine** [comment]
See #60 for a previous discussion on this topic.

We are not going to expose the CEL environment. The goal of [protovalidate](https://github.com/bufbuild/protovalidate) is for constraints to be portable across any implementation as the protos where the rules are defined might be run in any context. This means that the only supported custom CEL functions must be part of the protovalidate spec or defined as a custom CEL expression on the message/field itself. 

That said, if your validation rule is common enough, we're happy to discuss incorporating it as a standard constraint (a recent example is support for [IP/CIDR Prefixes](https://github.com/bufbuild/protovalidate/issues/66)). We're alternatively looking at ways to [share/reuse a CEL expression across multiple entities](https://github.com/bufbuild/protovalidate/issues/51).

As for your certificate example above, perhaps this goes a bit beyond the scope of protovalidate and into actual implementation of your service. I can see an `isX509` function to make sure the data is in the correct _shape_, but actually evaluating the cert data is signed by the CA probably belongs in your business logic.

**Comment by kralicky** [comment]
That is disappointing, but understandable I suppose. In my case, I am using protovalidate to standardize validation across a bunch of different APIs, which were previously all doing their own thing slightly differently. This way validations can be performed automatically and have all the context info from the descriptors.

My example code is a bit contrived, yes, and out of scope for any standard validators, but I wanted to give an example that made use of a few different features. The intent was a rigorous sanity-check, not a replacement for real backend logic, of course. :wink:
